### ISSUE TITLE
[Classic] Shaman color 

### ISSUE THREAD

**Issue by stefan0uh** [rgd87/Aptechka#17]
https://github.com/rgd87/Aptechka/blob/6485eb658ce5d606406cca4eef2bf02581013727/Aptechka.lua#L302-L310

you can set the shaman color globally, so all addons profit and the UI is not inconsistent

```
RAID_CLASS_COLORS['SHAMAN']["r"] = 0.25
RAID_CLASS_COLORS['SHAMAN']["g"] = 0.32
RAID_CLASS_COLORS['SHAMAN']["b"] = 0.96
RAID_CLASS_COLORS['SHAMAN']["colorStr"] = "ff4254f5"
```

**Comment by d87** [comment]
It'll cause taint most likely

**Comment by stefan0uh** [comment]
In other words, you don't want a consistent user experience?
Example PlayerFrames, Chat, Details are still pink but your frame is blue :D

After using the strings for weeks as a weak aura and it doesn't break any other addons.

**Comment by d87** [comment]
No, i don't want my addon causing taint ( https://wow.gamepedia.com/Secure_Execution_and_Tainting )
And even if it was safe to write to RAID_CLASS_COLORS, it's still not the place of unitframe addon to make these global changes. I did what i can to safely make it blue because i hate the pink too. The rest is either the responsiblity of chat addon etc authors, or the users who can install https://www.wowinterface.com/downloads/info25310-ShamanFix.html and then their taint is not my problem
