### ISSUE TITLE
question on performance and future plans

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#31]
Any comparisons done in terms of cpu usage/frame update... between this and other similar mods?
Additionally, are there any plans or roadmaps for future changes & updates to this mod?

Please don't take this question in a wrong way, but why I (as a healer) would want to use this addon which does not have "easy" way of customizing it? essentially what's the selling point of this.

Thanks in advance,

**Comment by d87** [comment]
Regarding performance basically the only part of raid frame addons that matters is aura handling, and it's pretty optimized here. If you're having any issues, which i doubt, you can disable debuff ordering.

I'm in the process of adding gui for widget customization. After that everything is going to be pretty easy, but console 
commands aren't terribly hard for now. That won't be on live until the prepatch, and classic is currently is even more behind, again until around prepatch. After that idk, there's nothing left to do. 

The selling poing historically for most people I guess would be that it "just werks" out of the box. That and maybe small things like the LOS warning, bars instead of icons/squares, native incoming casts, dungeon debuff highlights
And with the recent changes it's very customizable.
This is my least popular addon, despite being the best. Vast majority of people use blizzard frames, then there's elvui then grid2 and vuhdo, About this one no one even knows and nothing I do will change that, popular things stay popular.

**Comment by spamwax** [comment]
Thanks for your reply, I really don't care if it is popular or not as long as it makes my life easier and doesn't cause frame issues :)
I am going to give it a try on PTR and wait for the GUI for widgets.
How does addon know about new debuffs (and important debuffs for a healer to track) that get added, say, with a new expansion or a new tier patch? do you include it in the download or it has some sort of auto discovery feature?

**Comment by d87** [comment]
Latest SL version already has widget GUI btw.
I include default debuff highlights for some reactive dungeon trash abilities and stuff, but the game itself also has the concept of "boss auras", they're bigger
