### ISSUE TITLE
Questions (9.0-beta)

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#35]
1. I am guessing that Aptechka will automatically assign all dungeon and raid debuffs to the widget that's called `debufficons*`, right? At the moment there is no way to assign a spell to that widget as it does not appear under "Assign to" drop-down menu.

2. Related to above, "bossdebuff" widget item appears in "Assign to" list for a spell but I cannot find it in the "Widgets!" list. are these two somehow related? I tried to assign a spell (glimmer of light) to it but it didn't show up anywhere!

3. When the alternate power bar is added to frames (like sanity in nzoth fight), will it replace the current mana/energy bar automatically or I should add such a thing?

4. Is it possible to show all unit frames (can be empty) for testing purposes if I am not in a fully formed raid/group? can be helpful to adjust the location and sizes of frames before getting into content.

5. Is there a dedicated help page or Wiki somewhere to collect guides and answers to such questions for future users? I can do a PR for some Wiki pages if you are interested in that.

**Comment by d87** [comment]
1. debuff icons is a special case, they just directly show all the debuffs and only that, like for example target frame would. It's only a widget for the sake of customization, otherwise it's outside the normal loop.

2. bossdebuff currenly is an alias to border I think. Basically bossdebuff was an alert widget that blinked when one of the debuffs from _Debuff Highlights_ is present. It was also the default widget for DispelStatus, but after debuff slots became movable there was no longer a good spot for it. I'll remove it from the list or try to think of how to restore it

3. Nothing like that is present. I not sure if that type of data is even available for raid members without comms

4. No

5. Myself I only planned to do an overview of API to skin, make custom widgets, and toggle stuff from external code. Sure you can contribute.

**Comment by d87** [comment]
Yeah, seems sanity bar can be done. I'll add it probably similar to what DK runic power looks like.
