### ISSUE TITLE
Question: "Extend Below" & "Refresh Time" & "Others' Color"

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#41]
Hello
Can you please explain the "Extend Below" & "Refresh Time" textboxes available in Spell List?
What do they do? What's the intended use for them?

Also the same for "Max Count"?

**Comment by d87** [comment]
1. For example atonement's duration is 15s normally, and when you have 3s left on atonement and you press evangelism, the game will extend it, but API will report the new duration as 9s. Or when the Renewing Mist jumps it's duration on the new target is whatever time is left on it, not the initial 20s. So basically all spells that extend the aura are actually refreshing it to a new duration. And having bars at random speeds is annoying. With extend below you're setting a minimal possible duration, so extensions start looking like extensions no matter what the game tells the duration is.

2. Refresh time is for Pandemic on hots. It should be 30% of the original duration, then bar color becomes a little darker. It's pretty hard to tell apart, but pandemic on healers is also not useful at all.

3. Some spells like PoM or Earth Shield show charges instead of duration. The game doesn't tell what their upper limit is, so you need to manually specify it.

**Comment by spamwax** [comment]
1. So if I set Extend Below to 4 seconds and Renewing Mist jumps to a new target at 4 second or less I should see the same speed of bar animation for a 20sec Renewing Mist? what happens if RM jumps at 5 seconds? I am still confused about this :)

2. Is it possible to adjust the color of pandemic? For example I don't want to refresh my druid HoTs on targets if they are above the pandemic limit so maybe making the color more visible or customizable can help with that?

**Comment by d87** [comment]
Extend Below should be at least 20s for ReM. When i say duration i mean max duration, bars show timeLeft / duration. So when it jumps the game will return 6/6s for example. Which is very different from 6/20s

**Comment by spamwax** [comment]
OK, thanks.

**Comment by spamwax** [comment]
@d87
"Others' Color" is for when spell is not mine and "Casted by Player" is not checked? or it always shows other people's spell regardless of the checkbox?

**Comment by d87** [comment]
Yes, when casted by player is not checked. It's more relevant on classic where same hots from different people don't stack
