### ISSUE TITLE
Question about some of GUI options

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#47]
1. Under _Status List_ I now see `DebuffAlert1`, ... are these intended to be used with DBM/BigWigs alerts or...?
2. Under _Profile Setting_, There is a checkbox for `Dispel Indicator`. What's this for? How is it related to `Status List`->`Dispel`?
3. In _Debuff Highlighting_, options 1 and 2 of highlighting say red/pink *corner*, but when I test it the entire border of the frame lights up! Is that intended?
4. Anyway to adjust the color of corners/borders in debuff highlighting through GUI or Aptechka's command line?
5. This one is hard to test, is there a color difference for healing absorbs vs damage absorbs?

**Comment by d87** [comment]
1. Debuff Highlights have 4 levels or "importance". These alerts correspond to them
2. It disables it. It's just there since before Status List existed at all.
3. Tooltip is outdated. It used to be corner, but when everything became customizable i had to remove it and start using border for debuff alert. Personally i don't like it, but it's hard to find a spot that works in both horizontal and vertical mode by default
4. DebuffAlert1 - 4 are for that exactly
5. Heal absorbs are dark red and go down from the health level.
