### ISSUE TITLE
DebuffIcons Question

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#56]
Hey

1. Is it possible to remove the Border Style from the DebuffIcons widgets entirely? The information the border style (spell school, right?) provides is not that useful and it's taking valuable space.
2. Also how do I enable/show the number of stacks in Dispel status? I assigned it to my own icon widgets and other than color and scale I cannot get it to show the stacks? do I need to add a different text-only widget to do this?

**Comment by d87** [comment]
1. Done, 9.0.14-beta1
2. Any icon should show stacks as is.

**Comment by spamwax** [comment]
Thanks.

That's the problem I can't seem to make it show stacks, and it's difficult to test it. How do you test it? do you duel or there are some mobs around that can apply multiple stacks of debuf? :)

**Comment by d87** [comment]
I assume you're talking about stacks on DispelStatus, right?
Some nzoth assaults mobs apply stacking debuffs for sure. Tolvir with the magic debuff, shadowfiends with curse in the vale and maybe bugs in uldum do stacking poison.
I don't test stacks often, but otherwise there's Proving Grounds healer trials and mobs in mogu area near Dazar'alor apply curses and do casts.

**Comment by d87** [comment]
Tested it myself. You're right, stacks are missing, from ProgressIcon at least

**Comment by d87** [comment]
Alright, fixed in https://github.com/rgd87/Aptechka/releases/tag/9.0.14-beta2
