### ISSUE TITLE
Additional options for pet frames

### ISSUE THREAD

**Issue by ryandevries** [rgd87/Aptechka#84]
TBC Request

I would be grateful for some additional flexibility with regards to how the pet frames are placed, even if its just as simple as being able to pick top/left/right/bottom as where they anchor to.  Also, heal prediction doesn't seem to function on the pet frames.

**Comment by d87** [comment]
the reason it's like that is because addons don't have control over frame position in combat and I can't make pets a last group or embedded into player groups, because if someone joins in combat they'll overlap. So the only reasonable spot for it is either on it's own anchor or below the first group.
If prediction doesn't work on BCC it means LibHealComm doesn't work for pets

**Comment by d87** [comment]
But i'll maybe try some options

**Comment by ryandevries** [comment]
Makes sense, separate anchor would be nice but I can see why that may be annoying as well
