### ISSUE TITLE
Default transparency value when not in combat and has no target

### ISSUE THREAD

**Issue by meatGUY** [rgd87/Aptechka#88]
Is it possible to implement a support for default frames transparency when you aren't in combat a has no target? It is useful if you like (like I am) to not hide interface elements but rather make them transparent to 30-40% and make them reactivating when you have target or in combat.

**Comment by d87** [comment]
Try this https://www.curseforge.com/wow/addons/kingkongframefader
The global names of aptechka headers are NugRaid1, NugRaid2, etc. through 8
Part of the reason why I don't want to do it is because addons like king kong exist and if I'll start messing with alpha myself it'll interfere with their functionality

**Comment by meatGUY** [comment]
Hi @d87,

I have tried Kong and by far it works brilliantly - thank you very much for suggestion!
